"""initial

Revision ID: 868d6fdbe851
Revises: 
Create Date: 2026-07-01 10:11:34.967074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868d6fdbe851'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_records',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('context_md', sa.Text(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('translation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_rules_keyword'), 'translation_rules', ['keyword'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_rules_keyword'), table_name='translation_rules')
    op.drop_table('translation_rules')
    op.drop_table('task_records')
    # ### end Alembic commands ###
